---
title: "Limpeza e Tratamento de Dados: Taxa de Rotatividade"
output: html_notebook
---

```{r}
# Importando dados, string vazio = NA, string como fatores
data = read.csv("Churn.csv", sep = ";", na.strings = "", stringsAsFactors = T)
head(data)
summary(data)
```
Colunas
```{r}
# Renomeando as colunas
colnames(data) = c("Id", "Score", "Estado", "Genero", "Idade", "Patrimonio", "Saldo", "Produtos", "TemCartCredito", "Ativo", "Salario", "Saiu")
head(data)
```
Explorar Dados e Colunas Categóricas
```{r}
# Estados
counts = table(data$Estado)
barplot(counts, main = "Estados", xlab = "Estados")
# Genero
counts = table(data$Genero)
barplot(counts, main = "Gêneros", xlab = "Gêneros")
```
Explorando colunas numéricas
```{r}
# Score
summary(data$Score)
boxplot(data$Score)
hist(data$Score)
```

```{r}
# Idade
summary(data$Idade)
boxplot(data$Idade)
hist(data$Idade)
```

```{r}
# Saldo
summary(data$Saldo)
boxplot(data$Saldo)
hist(data$Saldo)
```

```{r}
# Salário
summary(data$Salario)
boxplot(data$Salario)
boxplot(data$Salario, outline = F)
```
Tratando valores não disponíveis (NA)
```{r}
#vendo os valores
data[!complete.cases(data),]
```
Salários
```{r}
#tratar salários
summary(data$Salario)
#ver mediana
median(data$Salario, na.rm = T)
#atribuir medianas à NAs
data[is.na(data$Salario),]$Salario = median(data$Salario, na.rm = T)
#checando remoção
data[!complete.cases(data$Salario),]
```
Falta de padronização em Gênero
```{r}
#ver valores
unique(data$Genero)
summary(data$Genero)
#transformar F e Fem em Feminino
# "" e M em Masculino (moda)
data[is.na(data$Genero) | data$Genero == "M",]$Genero = "Masculino"
data[data$Genero == "F" | data$Genero == "Fem",]$Genero = "Feminino"
#ver resultado
summary(data$Genero)
#removendo levels não utilizados
data$Genero = factor(data$Genero)
#visualizando novamente
summary(data$Genero)
```
Idades fora do domínio
```{r}
summary(data$Idade)
#vendo idades anormais
data[data$Idade < 0 | data$Idade > 110,]$Idade
#verificando NAs
data[is.na(data$Idade),]
#mediana
median(data$Idade)
#substituindo pela mediana
data[data$Idade < 0 | data$Idade > 110,]$Idade = median(data$Idade)
#verificando novamente idades anormais
data[data$Idade < 0 | data$Idade > 110,]
summary(data$Idade)
```
Dados Duplicados
```{r}
# buscar dados duplicados pelo ID
duplicated_data = data[duplicated(data$Id),]
duplicated_data
# eliminando o dado duplicado pelo índice
data = data[-c(82),]
# busca a linha duplicada
data[data$Id == duplicated_data$Id,]
# verifica a duplicação
duplicated_data = data[duplicated(data$Id),]
duplicated_data
```
Estado fora do domínio
```{r}
# fora do domínio - categórico
unique(data$Estado)
summary(data$Estado)
# preencher com a moda - RS
data[!data$Estado %in% c("RS", "SC", "PR"),]$Estado = "RS"
summary(data$Estado)
# removendo levels não utilizados
data$Estado = factor(data$Estado)
# visualizar novamente
summary(data$Estado)
```
Oultiers
```{r}
# criando parâmetro com desvio padrão - 2x da média
desv = sd(data$Salario, na.rm = T)
desv
data[data$Salario >= 2 * desv,]$Salario
# visualizando via gráfico
boxplot(data$Salario)
boxplot(data$Salario, outline = F)
x = boxplot(data$Salario)$out
x
# substitui pela mediana
median(data$Salario)
data[data$Salario >= 2 * desv,]$Salario = median(data$Salario)
# checa a remoção dos outliers
data[data$Salario >= 2 * desv,]$Salario
```
