---
title: "Gráficos e Dashboards - Teste Final do Bloco (Prática em R)"
output: html_notebook
---
Instalando pacote RColorBrewer
```{r}
# install.packages("RColorBrewer")
library("RColorBrewer")
```
Lendo arquivo
```{r}
data = read.csv("dados.csv", sep = ";")
head(data)
```
Resumo estatístico
```{r}
summary(data$VALOREMPENHO)
summary(data$PIB)
```
Gerando gráficos
```{r}
boxplot(data$VALOREMPENHO, main = "Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"), outline = F)
boxplot(data$PIB, main = "Produto Interno Bruto", col = brewer.pal(n = 3, name = "Pastel1"), outline = F)
hist(data$VALOREMPENHO, main = "Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"))
hist(data$PIB, main = "Produto Interno Bruto", col = brewer.pal(n = 3, name = "Pastel1"))
```
Buscando os maiores empenhos
```{r}
maior_empenho = head(data[order(-data$VALOREMPENHO),], 10)
barplot(maior_empenho$VALOREMPENHO, col = brewer.pal(n = 10, name = "RdBu"), las = 2, main = "Maiores Empenhos")
legend("topright", legend = maior_empenho$MUNICIPIO, col = brewer.pal(n = 10, name = "RdBu"), lty = 1:2, cex = 0.8, ncol = 2, lwd = 4)
box()
```
Maiores PIBs
```{r}
maior_pib = head(data[order(-data$PIB),], 10)
barplot(maior_pib$PIB, col = brewer.pal(n = 10, "Spectral"), las = 2, main = "Maiores PIBs")
legend("topright",legend = maior_pib$MUNICIPIO, col = brewer.pal(n = 10, name = "Spectral"), lty = 1:2, cex = 0.8, ncol = 2, lwd = 4)
box()
```
Relação entre PIB e Empenho
```{r}
# Calcula a porcentagem do PIB empenhado
data$PROPORCAO = data$VALOREMPENHO / data$PIB
maior_proporcao = head(data[order(-data$PROPORCAO),], 10)
barplot(maior_proporcao$PROPORCAO, col = brewer.pal(n = 10, name = "Set2"), las = 2, main = "Maiores Gastos em Proporção ao PIB")
legend("topright",legend = maior_proporcao$MUNICIPIO, col = brewer.pal(n = 10, name = "Set2"), lty = 1:2, cex = 0.8, ncol = 2, lwd = 4)
box()
```
