---
title: "Exercício da Aula - Pacote Lattica (Prática em R)"
output: html_notebook
---

```{r}
library(lattice)
```
Boxplot
```{r}
bwplot(trees$Volume)
bwplot(trees$Volume, main = "Árvores", xlab = "Volume")
```
Histograma
```{r}
# aspecto = proporção; nint = num de quebras; type = percent, count, density;
histogram(trees$Volume, main = "Árvores", xlab = "Volume", aspect = 1, type = "percent", nint = 5)
```
Histograma Condicional
```{r}
#Peso das galinhas de acordo com a alimentação
chickwts
#Histograma
histogram(chickwts$weight)
#Agregando os dados
aggregate(chickwts$weight, by = list(chickwts$feed), FUN = sum)
#Histograma condicional
histogram(~weight | feed, data = chickwts)
```
Gráfico de dispersão condicional
CO2, seis plantas em dois locais, refrigeradas ou não durante a noite
```{r}
# conc: concentração de co2, uptake: captação de co2
CO2
xyplot(CO2$conc ~ CO2$uptake)
# type é a origem
xyplot(CO2$conc ~ CO2$uptake | CO2$Type)
#refrigerado ou não
xyplot(CO2$conc ~ CO2$uptake | CO2$Treatment)
```
Cancer de esofago
agegp: idade, algcp: alcool, tobgp: tabaco
```{r}
esoph
dotplot(esoph$alcgp ~ esoph$ncontrols, data = esoph)
dotplot(esoph$alcgp ~ esoph$ncontrols | esoph$tobgp)
```
Matriz de dispersão
```{r}
splom(~CO2[4:5] | CO2$Type, CO2)
```
Densidade Condicional
```{r}
densityplot(~CO2$conc | CO2$Treatment, plot.points = F)
densityplot(CO2$conc)
densityplot(~CO2$conc | CO2$Treatment)
densityplot(~CO2$conc | CO2$Treatment, plot.points = F)
```
Gráfico 3D
Spray para repelir abelhas
```{r}
OrchardSprays
cloud(decrease ~ rowpos * colpos, data = OrchardSprays)
cloud(decrease ~ rowpos * colpos, groups = treatment, data = OrchardSprays)
```
Level plot
Circunferência, largula e altura de árvores
```{r}
trees
levelplot(Girth ~ Height * Volume, data = trees)
```
